export const DEFAULT_QUESTIONS_PROMPT =
  `Product: {productTitle}
{features}
{description}

Generate 5–8 concise questions that a reviewer should address when reviewing this category of products.
Focus on what matters most for this category (performance, usability, durability, value, etc.).
Return ONLY: {"questions": ["question 1", "question 2", ...]}`;

export const DEFAULT_SYSTEM_PROMPT =
  `You are an expert Amazon product reviewer. You write honest, balanced, and insightful reviews that help other customers make real purchasing decisions. Your reviews are specific and direct, explain the "why" behind every opinion, and avoid marketing language, hype, or superlatives.`;

export const DEFAULT_REVIEW_PROMPT =
  `Write an Amazon customer review based on the following.

Product: {productTitle}

Features:
{features}

Description:
{description}

My notes about this product:
{userNotes}

Characteristics I agree with from other buyer reviews (mention each one naturally in the review):
{characteristics}

My star rating: {starRating} out of 5 stars

Requirements:
- 200 to 400 words
- Never ever mention this review is generated by AI or anything about AI, LLM, language model, or anything like that. Do not mention the source of the review at all. Just write a normal review as if you were a regular customer.
- Useful and insightful — explain WHY, not just WHAT
- Honest and balanced — include real negatives if they come through in my notes
- Avoid promotional language, hype, or superlatives
- Don't duplicate product features if those are not used.
- Write a concise review title (max 120 characters, no surrounding quotes). 
- Make it sound like a real review, no ads, no bullshit.
- Don't make it sound like an essay "In this review blah blah blah".
- *Critical*. Don't make things up if I didn't mention those or didn't select those.
- If there are no positives or negatives, don't put those sections.
- No room for improvements comments unless I mention it.
- Do not repeat the product name.
- Do not put rating in the title or the description. Justifying rating is ok but there is no need to duplicate it.
- Do not repeat full product name in the description. Use model if needed but never to full name including manufacturer. 
- If user mentions specific models, numbers, characteristis, use those in the review, don't generalize or skip them.

Respond with valid JSON only, no other text:
{"title": "...", "body": "..."}`;
