// ---------------------------------------------------------------------------
// Product data extracted from the Amazon product page
// ---------------------------------------------------------------------------
export interface ProductInfo {
  asin: string;
  locale: string; // e.g. "amazon.ca"
  title: string;
  features: string[];
  description: string;
  avgRating: number | null;
  reviewCount: number | null;
}

// ---------------------------------------------------------------------------
// Review generated by OpenAI
// ---------------------------------------------------------------------------
export interface GeneratedReview {
  title: string;
  body: string;
}

// ---------------------------------------------------------------------------
// Transient storage payloads
// ---------------------------------------------------------------------------

/** Set by the vine-orders content script; read by the side panel. */
export interface ReviewTarget {
  asin: string;
  title: string;
  locale: string;
}

/** Set by the background when the user triggers form fill; read by review-form content script. */
export interface PendingFill {
  asin: string;
  locale: string;
  title: string;
  body: string;
  starRating: number;
}

// ---------------------------------------------------------------------------
// Persisted user settings
// ---------------------------------------------------------------------------
export interface Settings {
  apiEndpoint: string;
  openaiApiKey: string;
  openaiModel: string;
  systemPrompt: string;
  reviewPromptTemplate: string;
}

// ---------------------------------------------------------------------------
// Review characteristics extracted from existing customer reviews
// ---------------------------------------------------------------------------
export interface ReviewCharacteristic {
  text: string;                         // e.g. "easy to install"
  sentiment: 'positive' | 'negative';
  count: number;                        // times mentioned across scraped reviews
}

// ---------------------------------------------------------------------------
// Message bus (content ↔ background)
// ---------------------------------------------------------------------------
export type AppMessage =
  | { type: 'OPEN_REVIEW'; asin: string; title: string; locale: string }
  | { type: 'FETCH_PRODUCT'; asin: string; locale: string }
  | { type: 'FETCH_REVIEWS'; asin: string; locale: string }
  | { type: 'GENERATE_REVIEW'; product: ProductInfo; userNotes: string; starRating: number; checkedCharacteristics?: string[] }
  | { type: 'FILL_REVIEW_FORM'; asin: string; locale: string };

export type AppMessageResponse =
  | { ok: true }
  | { product: ProductInfo }
  | { review: GeneratedReview }
  | { error: string };
